### PR TITLE
Chests

### PR DESCRIPTION
**Pull request by TiagoFar78**
This PR was made in order to implement everything related to chests and other kind of containers arround the map.

### CODE REVIEW

**Comment by iquelli** [comment]
You have some commits that are not part of this PR

**Comment by TiagoFar78** [comment]
Isn't that supposed? I thought it was because of rebase.

**Comment by iquelli** [comment]
> Isn't that supposed? I thought it was because of rebase.

No, did u use push -f ?

**Comment by TiagoFar78** [comment]
I don't think that is a problem because this [commit ](https://github.com/TiagoFar78/PrisonEscape/pull/98/commits/d2e490d56118c5b7dd6936de574bf6734b283779) uses BukkitWorldEditorClass and in the changed files there is nothing like that. I don't think we need to worry.

**Comment by iquelli** [comment]
Okay, but next time do:

- git rebase master
- (solve conflicts)
- git push -f

**Review by iquelli — APPROVED** [review]

**Comment by TiagoFar78** [comment]
Thanks

**Pull request merged**
