### PR TITLE
Fix part of ugly formatter settings

### LINKED ISSUE #197: DOC: Ugly formatter setting
**Screenshots**
image

**Expected behavior**
image

This issue is a partition of #99

### PR DESCRIPTION
**Pull request by ana-mc-almeida**
This PR fixes part of #99 (closes #197)

 **Current behavior** 
321696061-42097036-c833-4d1b-804c-d31e9937b7d6

**Expected behavior** 
321695754-8bff2863-9dc7-4b4b-a69b-daa5e97f0416

**New behavior**
Screenshot_20240506_235941

### Note:
I only committed the formatter changes, but not the formatted code.

### CODE REVIEW

**Comment by iquelli** [comment]
Could u commit with the changes?

**Comment by TiagoFar78** [comment]
I think it is better to just apply the formatter to the code when the PR is completed. When every ugly aspect of the formatter is solved then the PR will be completed.

Doing this avoids multiple rebases. There will be only one rebase when the PR is completed.

**Comment by TiagoFar78** [comment]
You can now apply the formatter to finish this PR.

**Comment by iquelli** [comment]
@TiagoFar78 
I think we can merge this already
It didnt change much

**Review by TiagoFar78 — APPROVED** [review]

**Pull request merged**
